### ISSUE TITLE
Proxy feature request

### ISSUE THREAD

**Issue by n0x00** [Pickfordmatt/LinkedinCrawler#1]
Is it possible to get a proxy feature here ?

**Comment by Pickfordmatt** [comment]
Been thinking about this for a while now, will 100% look into it!

**Comment by ckhawks** [comment]
Will this ever be pushed?

**Comment by Pickfordmatt** [comment]
The tool moved away from accessing Linkedin and gathers the information from Yahoo, if you're experiencing blocks from the search engine I can 100% look into the proxy feature again.

**Comment by Pickfordmatt** [comment]
Proxy Added
