### ISSUE TITLE
Prowl no longer Works for me 

### ISSUE THREAD

**Issue by rezikom** [Pickfordmatt/LinkedinCrawler#12]
root@TigeRR:/home/tigerr# cd prowl
root@TigeRR:/home/tigerr/prowl# ls
file.py  file.pyc  prowl.py  README.md  requirements.txt  Version.txt
root@TigeRR:/home/tigerr/prowl# python prowl.py -c "Yahoo" -e "<fn><ln>@yahoo.com" -nj
__________________________________________________
 
    
  _____     ______    ______  ___  ___  ___ ___
 /      \  /      \  /      \ |  \ |  \ |  \| $$
|  $$$$$$\|  $$$$$$\|  $$$$$$\| $$ | $$ | $$| $$
| $$  | $$| $$   \$$| $$  | $$| $$ | $$ | $$| $$
| $$__/ $$| $$      | $$__/ $$| $$_/ $$_/ $$| $$
| $$    $$| $$       \$$    $$ \$$   $$   $$| $$
| $$$$$$$  \$$        \$$$$$$   \$$$$$\$$$$  \$$
| $$
| $$
 \$$    
         
Author: @MattSPickford
__________________________________________________

Traceback (most recent call last):
  File "prowl.py", line 50, in <module>
    import file
  File "/home/tigerr/prowl/file.py", line 4, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4
root@TigeRR:/home/tigerr/prowl#

**Comment by Pickfordmatt** [comment]
Are you running on a new machine?

try: pip install bs4
