### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by zeknox** [Pickfordmatt/LinkedinCrawler#13]
Running the latest version (commit: 2deb5614e0d009c1c0eb56eb9dfbf4e3bea2c884) of Prowl on Kali linux and the tool is running the following error when performing a basic search.

<pre>
BING
-----------------------------------------------------------------------------------------------------------------------------         
Traceback (most recent call last):
  File "./prowl.py", line 53, in <module>
    import file
  File "/root/Tools/Prowl/file.py", line 236, in <module>
    bing(args.company, args.emailformat)
  File "/root/Tools/Prowl/file.py", line 112, in bing
    fulljob = tag.find("li").text
AttributeError: 'NoneType' object has no attribute 'text'
</pre>

**Comment by Pickfordmatt** [comment]
Thanks for input, should be fixed now :) 


My twitter is @mattspickford if you want faster replies

**Comment by Pickfordmatt** [comment]
Has that worked for you?

**Comment by zeknox** [comment]
Thanks for the follow up, the latest version fixed the issue for me, cheers!
